import express from 'express';
import { requireAuth, verifyDocumentOwnership } from '../middleware/auth.js';

const router = express.Router();

/**
 * Generate clean printable HTML with typography and print CSS
 */
function renderPrintableHtml(document) {
  const title = document.title || 'Vani AI Document';
  const type = (document.type || 'DOCUMENT').toUpperCase();
  const content = document.content || '';

  // Simple clean markdown-to-HTML formatting for common elements
  const formattedBody = content
    .replace(/^### (.*$)/gim, '<h3 style="color: #1e1b4b; margin-top: 18px; margin-bottom: 8px;">$1</h3>')
    .replace(/^## (.*$)/gim, '<h2 style="color: #312e81; border-bottom: 1px solid #e2e8f0; padding-bottom: 6px; margin-top: 24px; margin-bottom: 12px;">$1</h2>')
    .replace(/^# (.*$)/gim, '<h1 style="color: #1e1b4b; border-bottom: 2px solid #6366f1; padding-bottom: 8px; margin-bottom: 16px;">$1</h1>')
    .replace(/\*\*(.*?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.*?)\*/g, '<em>$1</em>')
    .replace(/^- (.*$)/gim, '<li style="margin-bottom: 4px;">$1</li>')
    .replace(/\n\n/g, '<p style="margin-bottom: 12px; line-height: 1.6;"></p>');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${title}</title>
  <style>
    @page { margin: 20mm; size: A4; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif;
      color: #0f172a;
      background: #ffffff;
      margin: 0;
      padding: 30px;
      font-size: 13pt;
      line-height: 1.6;
    }
    .header {
      border-bottom: 2px solid #4f46e5;
      padding-bottom: 15px;
      margin-bottom: 25px;
    }
    .badge {
      display: inline-block;
      padding: 3px 8px;
      font-size: 10pt;
      font-weight: bold;
      background: #e0e7ff;
      color: #3730a3;
      border-radius: 4px;
      text-transform: uppercase;
      margin-bottom: 8px;
    }
    .meta {
      font-size: 9pt;
      color: #64748b;
      margin-top: 6px;
    }
    ul { padding-left: 20px; }
    @media print {
      body { padding: 0; }
      .no-print { display: none !important; }
    }
  </style>
</head>
<body>
  <div class="no-print" style="margin-bottom: 20px; padding: 12px; background: #f8fafc; border: 1px solid #cbd5e1; border-radius: 6px; display: flex; justify-content: space-between; align-items: center;">
    <span style="font-size: 12px; color: #475569;">Ready for printing or saving as PDF via your browser Print dialog.</span>
    <button onclick="window.print()" style="background: #4f46e5; color: #fff; border: none; padding: 6px 14px; border-radius: 4px; cursor: pointer; font-weight: 600;">Print / Save as PDF</button>
  </div>
  <div class="header">
    <span class="badge">${type}</span>
    <h1 style="margin: 0; color: #0f172a; font-size: 24pt;">${title}</h1>
    <div class="meta">Generated by Vani AI • ${new Date(document.updatedAt || Date.now()).toLocaleDateString('en-IN', { dateStyle: 'long' })}</div>
  </div>
  <div class="content">
    ${formattedBody}
  </div>
</body>
</html>`;
}

// GET /api/export/:id/:format
// Export a document in Markdown, JSON, Text, or clean Printable HTML (ensures ownership)
router.get('/:id/:format', requireAuth, async (req, res) => {
  const { id, format } = req.params;

  try {
    const document = await verifyDocumentOwnership(id, req.authUser.id);
    const sanitizedTitle = (document.title || 'document').replace(/[^a-zA-Z0-9_-]/g, '_');

    if (format === 'md' || format === 'markdown') {
      res.setHeader('Content-Type', 'text/markdown; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename="${sanitizedTitle}.md"`);
      return res.send(document.content);
    }

    if (format === 'json') {
      res.setHeader('Content-Type', 'application/json; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename="${sanitizedTitle}.json"`);
      return res.json({
        id: document.id,
        title: document.title,
        type: document.type,
        content: document.content,
        metadata: document.metadata,
        tasks: document.tasks || [],
        updatedAt: document.updatedAt
      });
    }

    if (format === 'txt' || format === 'text') {
      res.setHeader('Content-Type', 'text/plain; charset=utf-8');
      res.setHeader('Content-Disposition', `attachment; filename="${sanitizedTitle}.txt"`);
      return res.send(document.content);
    }

    if (format === 'html' || format === 'print' || format === 'pdf') {
      res.setHeader('Content-Type', 'text/html; charset=utf-8');
      return res.send(renderPrintableHtml(document));
    }

    return res.status(400).json({
      error: `Unsupported format '${format}'. Supported formats: md, json, txt, html. For PDF, use the HTML/Print view and select 'Save as PDF'.`,
      code: 'UNSUPPORTED_FORMAT'
    });

  } catch (error) {
    console.error('Export failed:', error.message);
    res.status(error.status || 500).json({
      error: error.message || 'Export failed',
      code: error.code || 'EXPORT_FAILED'
    });
  }
});

export default router;
